"""empty message

Revision ID: 134677c6f185
Revises: 
Create Date: 2018-07-05 14:44:22.237540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '134677c6f185'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctoruser', sa.Column('pass_hash', sa.String(length=255), nullable=True))
    op.add_column('doctoruser', sa.Column('passw_secure', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctoruser', 'passw_secure')
    op.drop_column('doctoruser', 'pass_hash')
    # ### end Alembic commands ###
