"""empty message

Revision ID: 2ca786320ac2
Revises: aa26a906d23c
Create Date: 2018-07-06 10:39:22.606453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ca786320ac2'
down_revision = 'aa26a906d23c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('notification_recieve_id_fkey', 'notification', type_='foreignkey')
    op.drop_constraint('notification_send_id_fkey', 'notification', type_='foreignkey')
    op.create_foreign_key(None, 'notification', 'patientuser', ['user_id'], ['id'])
    op.drop_column('notification', 'recieve_id')
    op.drop_column('notification', 'send_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('send_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('notification', sa.Column('recieve_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'notification', type_='foreignkey')
    op.create_foreign_key('notification_send_id_fkey', 'notification', 'patientuser', ['send_id'], ['id'])
    op.create_foreign_key('notification_recieve_id_fkey', 'notification', 'patientuser', ['recieve_id'], ['id'])
    op.drop_column('notification', 'user_id')
    # ### end Alembic commands ###
